# These are supported funding model platforms

[Gavinok]: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
[gavinfreeborn]: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
