#!/usr/bin/env sh

######################################################################
# @author      : Gavin Jaeger-Freeborn (gavinfreeborn@gmail.com)
# @file        : balsamiq.sh
# @created     : Sun 14 Jun 2020 02:43:10 PM
#
# @description : quick way to open Balsamiq as a webapp
######################################################################

google-chrome-stable --app="https://balsamiq-wireframes.appspot.com/"

# vim: set tw=78 ts=2 et sw=2 sr:
