#!/bin/bash
xrandr --output VIRTUAL1 --off --output DP3 --off --output DP2 --off --output DP1 --off --output HDMI2 --mode 1280x1024 --pos 1584x0 --rotate normal --output HDMI1 --off --output LVDS1 --primary --mode 1440x900 --pos 0x0 --rotate normal --output VGA1 --off
i3-msg "restart"
~/.fehbg
