#!/bin/sh
PROMPT="PROMPT"
while getopts ':p:' c
do
  case $c in
      p) PROMPT="$OPTARG" ;;
      
  esac
done

options=""
while read line
do
    options="$options \"$line\""
done

result=$(emacsclient -e "(completing-read \"$PROMPT \" '($options))" 2> /dev/null)
[ -z "$result" ] && exit 1 # if empty exit

printf "%s" "$result" | sed 's/"$//; s/^"//'

