#!/bin/sh
# quick and dirty Lorem ipsum
# originally from https://github.com/pjfichet/stuff/blob/master/scripts/lorem

echo "Lorem ipsum dolor sit amet, consectetuer adipiscing
elit. Sed non risus. Suspendisse lectus tortor, dignissim
sitamet, adipiscing nec, ultricies sed, dolor. Cras
elementum ultrices diam. Maecenas ligula massa, varius a,
semper congue, euismod non, mi. Proinporttitor, orci nec
nonum molestie, enim est eleifend mi, non fermentum diamnis
sit amet erat. Duis semper. Duisarcu massa, scelerisque
vitae, consequatin, pretium a, enim. Pellentesque congue. Ut
in risus volutpat liberopharetra tempor. Cras vestibulum
bibendum augue. Praesent egestas leo inpede. Praesent
blandit odio eu enim. Pellentesque sed dui ut augue blandit
sodales. Vestibulum ante ipsum primis infaucibus orci luctus
et ultrices posuere cubilia Curae. Aliquam nibh. Mauris
acmauris sed pede pellentesque fermentum. Maecenas
adipiscing ante non diamsodales hendrerit. Ut velit mauris,
egestas sed, gravida nec, ornare ut, mi. Aenean ut orci vel
massa suscipit pulvinar. Nulla sollicitudin. Fuscevarius,
ligula non tempus aliquam, nunc turpis ullam corper nibh, in
tempus. sapien eros vitae ligula. Pellentesque rhoncus nunc
et augue. Integer id felis. Curabitur aliquet pellentesque
diam. Integer quis metus vitae elit lobortis egestas."
