#!/usr/bin/env bash
#
# http://github.com/mitchweaver/bin
#
# play a video on the root window
#

[ -f "$1" ] || exit 1

pkill -9 xwinwrap

xwin="xwinwrap -ni -sh rectangle -b -nf -ov -fs -- "

mpv="mpv --wid WID --no-config \
	--panscan=1.0 \
	--mute=yes \
	--sid=no \
	--video-unscaled=no \
	--loop \
    --no-border --vd-lavc-fast --x11-bypass-compositor=no \
    --gapless-audio=yes --hwdec=auto\
    --name=mpvbg"

#	--start=+02:00 \
$xwin $mpv "$1" > /dev/null 2>&1 &
echo -n $! > ${HOME}/.cache/mpvbg.pid
