#!/bin/bash
mkdir ~/Documents/Dotfiles/
mkdir ~/Documents/Dotfiles/.config
mkdir ~/Documents/Dotfiles/.scripts
mkdir ~/Documents/Dotfiles/.calcurse/
setsid cp -u ~/.calcurse/todo ~/Documents/Dotfiles/.calcurse/todo &
mkdir ~/Documents/Dotfiles/.config/i3/
setsid cp -u ~/.config/i3/config ~/Documents/Dotfiles/.config/i3/config &
mkdir ~/Documents/Dotfiles/.config/mpv/
setsid cp -u ~/.config/mpv/input.conf ~/Documents/Dotfiles/.config/mpv/input.conf &
mkdir ~/Documents/Dotfiles/.config/
setsid cp -u ~/.config/compton.conf ~/Documents/Dotfiles/.config/compton.conf &
mkdir ~/Documents/Dotfiles/.config/anime-downloader/
setsid cp -u ~/.config/anime-downloader/watch.json ~/Documents/Dotfiles/.config/anime-downloader/watch.json &
mkdir ~/Documents/Dotfiles/.config/anime-downloader/
setsid cp -u ~/.config/anime-downloader/config.json ~/Documents/Dotfiles/.config/anime-downloader/config.json &
mkdir ~/Documents/Dotfiles/.config/dmenu/
setsid cp -u ~/.config/dmenu/config.h ~/Documents/Dotfiles/.config/dmenu/config.h &
mkdir ~/Documents/Dotfiles/.config/dmenu/
setsid cp -u ~/.config/dmenu/config.h ~/Documents/Dotfiles/.config/dmenu/config.h &
mkdir ~/Documents/Dotfiles/.config/dunst/
setsid cp -u ~/.config/dunst/dunstrc ~/Documents/Dotfiles/.config/dunst/dunstrc &
mkdir ~/Documents/Dotfiles/.config/keynav/
setsid cp -u ~/.config/keynav/keynavrc ~/Documents/Dotfiles/.config/keynav/keynavrc &
mkdir ~/Documents/Dotfiles/.config/newsboat/
setsid cp -u ~/.config/newsboat/config ~/Documents/Dotfiles/.config/newsboat/config &
mkdir ~/Documents/Dotfiles/.config/newsboat/
setsid cp -u ~/.config/newsboat/urls ~/Documents/Dotfiles/.config/newsboat/urls &
mkdir ~/Documents/Dotfiles/.config/nvim/
setsid cp -u ~/.config/nvim/init.vim ~/Documents/Dotfiles/.config/nvim/init.vim &
mkdir ~/Documents/Dotfiles/.config/polybar/
setsid cp -u ~/.config/polybar/config ~/Documents/Dotfiles/.config/polybar/config &
mkdir ~/Documents/Dotfiles/.config/ranger/
setsid cp -u -r ~/.config/ranger/ ~/Documents/Dotfiles/.config/ranger/ &
mkdir ~/Documents/Dotfiles/.config/rtv/
setsid cp -u ~/.config/rtv/rtv.cfg ~/Documents/Dotfiles/rtv/rtv.cfg &
mkdir ~/Documents/Dotfiles/.config/st/
setsid cp -u ~/.config/st/st.h ~/Documents/Dotfiles/.config/st/st.h &
mkdir ~/Documents/Dotfiles/.config/youtube-viewer/
setsid cp -u ~/.config/youtube-viewer/youtube-viewer.conf ~/Documents/Dotfiles/.config/youtube-viewer/youtube-viewer.conf &
mkdir ~/Documents/Dotfiles/.config/zathura/
setsid cp -u ~/.config/zathura/zathurarc ~/Documents/Dotfiles/.config/zathura/zathurarc &
mkdir ~/Documents/Dotfiles/.config/redshift/
setsid cp -u ~/.config/redshift/redshift.conf ~/Documents/Dotfiles/.config/redshift/redshift.conf &

mkdir ~/Dotfiles/.w3m
setsid cp -r -u ~/.w3m ~/Dotfiles/.w3m &

setsid cp -u ~/.bashrc ~/Dotfiles/.bashrc &
setsid cp -u ~/.tmux.conf ~/Dotfiles/.tmux.conf &
setsid cp -u ~/.vimrc ~/Dotfiles/.vimrc 
setsid cp -u ~/.xinitrc ~/Dotfiles/.xinitrc &
setsid cp -u ~/.Xresources ~/Dotfiles/.Xresources &
setsid cp -u ~/.shortcuts ~/Dotfiles/.shortcuts
setsid cp -u ~/.profile ~/Dotfiles/.profile &
setsid cp -u ~/.fehbg ~/Dotfiles/.fehbg &

setsid cp -u -r ~/.scripts/ ~/Dotfiles/ &
