#!/bin/bash

# Increase key speed via a rate change
xset r rate 200 50
# Map the caps lock key to super...
setxkbmap -layout us -variant altgr-intl -option caps:ctrl_modifier
#Map both shift Keys to capslock
setxkbmap -option "shift:both_capslock"
# If you don't want a us international keyboard, rather whatever keyboard
# you set in your installation, comment out the above line and uncomment
# the one below.

#h
xmodmap -e "keycode 43 = Left"
#j
xmodmap -e "keycode 44 = Down"
#k
xmodmap -e "keycode 45 = Up"
#l
xmodmap -e "keycode 46 = Right"
#x
xmodmap -e "keycode 53 = Delete"
#d
xmodmap -e "keycode 40 = BackSpace"
#s
xmodmap -e "keycode 39 = Delete"

spare_modifier="Hyper_L"

xmodmap -e "keycode 65 = $spare_modifier"
# Map space to an unused keycode (to keep it around for xcape to
# use).
xmodmap -e "keycode any = space"

# But when it is pressed only once, treat it as escape.
killall xcape ; xcape -e 'Caps_Lock=Escape'

xcape -e "$spare_modifier=space"

xcape -e 'Shift_R=Escape'


