#!/bin/sh
# Feed this script a link and it will give dmenu
# some choice programs to use to open it.
# TODO
# 1. Check if a program is installed before offering the option

Ifinstalled() {
	command -v "$1" >/dev/null || { notify-send "📦 <b>$1</b> must be installed for this function." && exit 1; }
}

torrent(){
	Ifinstalled transadd && transadd "${1}" && exit
	Ifinstalled aria2c && aria2c "${1}" && exit
	notify-send "No Torrent Program installed"
}

youtube(){
			notify-send "downloading video"
			setsid youtube-dl --add-metadata -i -o "$HOME/Downloads/%(title)s.%(ext)s" "${1}" \
				&& notify-send "finished download" && exit
			notify-send "failed downloading"
}

clone(){

			repo=$(echo "$1" | cut -d# -f1)
			repo=${repo}.git
			notify-send "cloning repository ${repo}"
			git -C "$HOME/Downloads/" clone "${repo}" \
				&& notify-send "finished cloning" && exit
			notify-send "failed cloning"
}

raw(){

			notify-send "downloading page"
			wget -P "$HOME/Downloads/" "${1}"   \
				&& notify-send "finished downloading" && exit
			notify-send "failed cloning"
}

downloader (){
	case "$1" in 
	    *magnet:*|*torrent*) 
	    	torrent "${1}";;
	    *youtube.com/watch* | *youtube.com/playlist*|*youtu.be*) 
			youtube "${1}" ;;
	    *github.com*|*gitlab.com*) 
			clone "${1}" ;;
	    *) 
			raw "${1}" ;;
	esac
	notify-send "failed downloading"
 	exit
}

x="$(printf "chrome\\nbrowser\\nmpv\\ndownload\\nkdeconnect\\nQR\\nyt\\ncast" | dmenu -i -p "Open link with what program?")"
case "${x}" in
    chrome) 
		setsid google-chrome-stable "$1" >/dev/null 2>&1 & ;;
    browser) 
		setsid "$TRUEBROWSER $1" >/dev/null 2>&1 & ;;
    cast) 
		setsid cast "$1" 2>&1 ;;
    QR)  
		qrencode "$1" -s 10 -o /tmp/QR.png  "$1"
		xdg-open /tmp/QR.png >/dev/null 2>&1 &;;
    mpv) 
		notify-send "playing video" && mpv "$1" >/dev/null 2>&1
 		notify-send "failed to play video" ;;
    kdeconnect)  
		kdeconnect-handler "$1" >/dev/null 2>&1 &;;
    yt) 
		ytplay "$1" >/dev/null 2>&1 || notify-send "failed to play video" ;;
    download) 
		downloader "$1" ;;
    *) 
		exit 1;;
esac
#vim:ft=sh
