#!/bin/sh

# quickly find and display man page

# LAUNCER="dmenu -i -l 20 -p "
[ -n "${DISPLAY}" ] && LAUNCER="fzf --prompt "

Selected="$(man -k . | $LAUNCER "Select Program " | cut -d" " -f1)"
man "$Selected"
#vim:ft=sh
