#!/bin/sh

# If transmission-daemon is running, will ask to kill, else will ask to start.

LAUNCER="emenu -i -p "

if pgrep -x transmission-da; then
	yn=$(printf 'No\nYes\n' | $LAUNCER "Kill transmission-daemon?")
	[ "$yn" = "Yes" ] && transmission-remote --exit
else
	yn=$(printf 'No\nYes\n' | $LAUNCER "Start transmission daemon?")
	[ "$yn" = "Yes" ] && transmission-daemon
fi
#vim:ft=sh
