#!/bin/dash

LAUNCER="dmenu"

vidlist="
Bash script		https://www.youtube.com/watch?v=YOpeXETS2z0&t=192s
Bash script full	 https://www.youtube.com/watch?v=oxuRxtrO2Ag	
dmenu script	https://www.youtube.com/watch?v=R9m723tAurA
status bar	https://www.youtube.com/watch?v=gKumet6b-WY
mutt		https://www.youtube.com/watch?v=2U3vRbF7v5A
ncmpcpp		https://www.youtube.com/watch?v=sZIEdI9TS2U
newsboat	https://www.youtube.com/watch?v=dUFCRqs822w
ranger		https://www.youtube.com/watch?v=L6Vu7WPkoJo
gpg keys	https://www.youtube.com/watch?v=DMGIlj7u7Eo
urlview		https://www.youtube.com/watch?v=IgzpAjFgbCw
ncurses		https://www.youtube.com/watch?v=2tWN6ntNo4w
SQL	https://www.youtube.com/watch?v=bEtnYWuo2Bw
SQL Full	https://www.youtube.com/watch?v=HXV3zeQKqGY&t=4342s
C programming	https://www.youtube.com/watch?v=2NWeucMKrLI&index=1&list=PL6gx4Cwl9DGAKIXv8Yr6nhGJ9Vlcjyymq
C File I/O	https://www.youtube.com/watch?v=-LqUMHoBo6o
C Error Handling	https://www.youtube.com/watch?v=IZiUT-ipnj0
install latex	https://www.youtube.com/watch?v=NwnYHoNtfJ0
Latex all	https://m.youtube.com/watch?v=VhmkLrOjLsw
Latex1		https://www.youtube.com/watch?v=mfRmmZ_84Mw&t=2s
Latex2		https://www.youtube.com/watch?v=25LExaNtdF0 
Latex3 bib	https://www.youtube.com/watch?v=46piog3Fzp4
Latex Resume	https://www.youtube.com/watch?v=VjsX4tznW40&t=570s
Latex Resume2	https://www.youtube.com/watch?v=o5-BZ7JmYWk	
Latex Images	https://www.youtube.com/watch?v=zgThRPjy-vw
Latex Macros	https://www.youtube.com/watch?v=rvgP7IMeUn8
Latex and vim	https://www.youtube.com/watch?v=yNOkCYuPt3E
Python		https://www.youtube.com/watch?v=rfscVS0vtbw&t=2s
JSON	https://www.youtube.com/watch?v=wI1CWzNtE-M
JavaScript	https://www.youtube.com/watch?v=W6NZfCO5SIk
Go 7 hour Course	https://www.youtube.com/watch?v=YS4e4q9oBaU&t=2h19m0s
Regex	https://www.youtube.com/watch?v=vcRPNhLbhoc
Game Dev in C	https://www.youtube.com/watch?v=yFLa3ln16w0&t=556s
Red Hat Linux Course complete	https://www.youtube.com/watch?v=oflN6WZOzxw
Full ArchLinux Install	    https://www.youtube.com/watch?v=4PBqpX0_UOc&t=1473s
Power of Unix	https://www.youtube.com/watch?v=7uwW20odwEk
Manjaro Architect   https://www.youtube.com/watch?v=530O4InhR3A
POSIX pthreads	https://www.youtube.com/watch?v=ynCc-v0K-do&list=PLzCAxcRKUAgkc65DlRo0gr0B8sqlE6WZY
groff	https://www.youtube.com/watch?v=w8EKH_fjmXA
groff Macros + Others	https://www.youtube.com/watch?v=kJ_TXZB4Gm4
groff enq	https://www.youtube.com/watch?v=sp0qgpeG6EY
groff refer	https://www.youtube.com/watch?v=XfOwRYmb5bQ&list=PL-p5XmQHB_JRe2YeaMjPTKXSc5FqJZ_km&index=4&t=0s
groff auto refer	https://www.youtube.com/watch?v=yTQbi_E_Gys&list=PL-p5XmQHB_JRe2YeaMjPTKXSc5FqJZ_km&index=4
rclone	https://www.youtube.com/watch?v=G8YMspboIXs
Arch Linux Maintenance	https://www.youtube.com/watch?v=3BnHHP7Fmo0
"


if command -v ytplay >/dev/null;then
	Player='ytplay'
else
	Player='mpv'
fi
echo "${vidlist}" | grep -P "^$(echo "${vidlist}" | grep "https:" | sed 's/\t.*//g' | ${LAUNCER} -i -p "Learn about what? (ESC to cancel)" -l 20 | awk '{print $1}')\s" | sed 's/.*\t//' | xargs -r ${Player}
#vim:ft=sh
