#!/bin/sh

# LAUNCER="dmenu -i -l 20 -p "
LAUNCER="emenu -p "
[ -z "${DISPLAY}" ] && LAUNCER="fzf --prompt"

vidlist="
Bash script		https://www.youtube.com/watch?v=YOpeXETS2z0&t=192s
Bash script full	 https://www.youtube.com/watch?v=oxuRxtrO2Ag
dmenu script	https://www.youtube.com/watch?v=R9m723tAurA
status bar	https://www.youtube.com/watch?v=gKumet6b-WY
mutt	https://www.youtube.com/watch?v=2U3vRbF7v5A
ncmpcpp		https://www.youtube.com/watch?v=sZIEdI9TS2U
newsboat	https://www.youtube.com/watch?v=dUFCRqs822w
ranger		https://www.youtube.com/watch?v=L6Vu7WPkoJo
gpg keys	https://www.youtube.com/watch?v=DMGIlj7u7Eo
urlview		https://www.youtube.com/watch?v=IgzpAjFgbCw
ncurses		https://www.youtube.com/watch?v=2tWN6ntNo4w
SQL	https://www.youtube.com/watch?v=bEtnYWuo2Bw
SQL Full	https://www.youtube.com/watch?v=HXV3zeQKqGY&t=4342s
C programming	https://www.youtube.com/watch?v=2NWeucMKrLI&index=1&list=PL6gx4Cwl9DGAKIXv8Yr6nhGJ9Vlcjyymq
C File I/O	https://www.youtube.com/watch?v=-LqUMHoBo6o
C Error Handling	https://www.youtube.com/watch?v=IZiUT-ipnj0
install latex	https://www.youtube.com/watch?v=NwnYHoNtfJ0
Latex all	https://m.youtube.com/watch?v=VhmkLrOjLsw
Latex1		https://www.youtube.com/watch?v=mfRmmZ_84Mw&t=2s
Latex2		https://www.youtube.com/watch?v=25LExaNtdF0
Latex bib	https://www.youtube.com/watch?v=46piog3Fzp4
Latex Resume	https://www.youtube.com/watch?v=VjsX4tznW40&t=570s
Latex Resume2	https://www.youtube.com/watch?v=o5-BZ7JmYWk
Latex Images	https://www.youtube.com/watch?v=zgThRPjy-vw
Latex Macros	https://www.youtube.com/watch?v=rvgP7IMeUn8
Latex and vim	https://www.youtube.com/watch?v=yNOkCYuPt3E
Python		https://www.youtube.com/watch?v=rfscVS0vtbw&t=2s
JSON	https://www.youtube.com/watch?v=wI1CWzNtE-M
JavaScript	https://www.youtube.com/watch?v=W6NZfCO5SIk
Go 7 hour Course	https://www.youtube.com/watch?v=YS4e4q9oBaU&t=2h19m0s
Regex	https://www.youtube.com/watch?v=vcRPNhLbhoc
Game Dev in C	https://www.youtube.com/watch?v=yFLa3ln16w0&t=556s
Red Hat Linux Course complete	https://www.youtube.com/watch?v=oflN6WZOzxw
Full ArchLinux Install	    https://www.youtube.com/watch?v=4PBqpX0_UOc&t=1473s
Power of Unix	https://www.youtube.com/watch?v=7uwW20odwEk
Manjaro Architect	https://www.youtube.com/watch?v=530O4InhR3A
POSIX pthreads	https://www.youtube.com/watch?v=ynCc-v0K-do&list=PLzCAxcRKUAgkc65DlRo0gr0B8sqlE6WZY
groff	https://www.youtube.com/watch?v=w8EKH_fjmXA
groff Macros and Others	https://www.youtube.com/watch?v=kJ_TXZB4Gm4
groff refer	https://www.youtube.com/watch?v=XfOwRYmb5bQ&list=PL-p5XmQHB_JRe2YeaMjPTKXSc5FqJZ_km&index=4&t=0s
groff auto refer	https://www.youtube.com/watch?v=yTQbi_E_Gys&list=PL-p5XmQHB_JRe2YeaMjPTKXSc5FqJZ_km&index=4
eqn groff 	https://www.youtube.com/watch?v=sp0qgpeG6EY
rclone	https://www.youtube.com/watch?v=G8YMspboIXs
Arch Linux Maintenance	https://www.youtube.com/watch?v=3BnHHP7Fmo0
Awk	https://www.youtube.com/watch?v=_q6Uj4X_knc
Hacking with Vim	https://www.youtube.com/watch?v=l8iXMgk2nnY
mutt isync	https://www.youtube.com/watch?v=tR9zk3xz5SA
ffmpeg screen casting	https://www.youtube.com/watch?v=386Z2yeQ5fo
installing fonts	https://www.youtube.com/watch?v=LJ7CEhnS0OM
cs50 Beyond javascript https://www.youtube.com/watch?v=dlEPkLSDQi0&t=51s
cs50 Beyond javascript continued https://www.youtube.com/watch?v=XNDZ3eg_VcE&t=319s
spotifyd https://www.youtube.com/watch?v=R5jikGfSdh4
hugo netlify github pages https://www.youtube.com/watch?v=NSts93C9UeE
Lua	https://www.youtube.com/watch?v=iMacxZQMPXs
Gnu Parallel	https://www.youtube.com/playlist?list=PL284C9FF2488BC6D1
Curl for REST APIs	https://www.youtube.com/watch?v=czeIHABQCxo
ImageMagick transparency	https://www.youtube.com/watch?v=D8pcvkRsx1g&t=300s
ImageMagick Canvases, Plasma, Composites, Geometry	https://www.youtube.com/watch?v=nbXHbHrfrIs
hub	https://www.youtube.com/watch?v=xWbaKNFAh8Y
valgrind https://www.youtube.com/watch?v=bb1bTJtgXrI
pass	https://www.youtube.com/watch?v=sVkURNfxPd4
discord bridge	https://www.youtube.com/watch?v=xIOyc4Rklqc&t=317s
"

pdfs="
pic for image drawing PDF	http://floppsie.comp.glam.ac.uk/Glamorgan/gaius/web/pic.html
pic Revised User Manual PDF	http://doc.cat-v.org/unix/v8/picmemo.pdf
tbl PDF	http://doc.cat-v.org/unix/v10/10thEdMan/tbl.pdf
eqn PDF	http://www.kohala.com/start/troff/v7man/eqn/eqn2e.ps
refer PDF	http://www.kohala.com/start/troff/v7man/refer/refer.ps
grap PDF	http://doc.cat-v.org/unix/v8/grap.pdf
unix text processing (utp) PDF	https://github.com/larrykollar/Unix-Text-Processing/releases/download/1.0/utp-1.0.pdf
pdf manipulation in groff with pdfmark PDF	http://pipeline.lbl.gov/code/3rd_party/licenses.win/groff/1.19.2/pdf/pdfmark.pdf
pdfmark.ms PDF	http://git.savannah.gnu.org/cgit/groff.git/plain/contrib/pdfmark/pdfmark.ms
general troff tutorial PDF	http://www.kohala.com/start/troff/v7man/trofftut/trofftut.ps
Troff User Manual PDF	http://doc.cat-v.org/plan_9/4th_edition/papers/troff.pdf
Groff and Friends HOWTO PDF	https://www.troff.org/TheGroffFriendsHowto.pdf
mom macros PDF	http://www.schaffter.ca/mom/pdf/mom-pdf.pdf
ms macros PDF	http://www.kohala.com/start/troff/v7man/msmacros/msmacros.ps
"
tutorials="
${vidlist}
${pdfs}
"

# TODO: grep for youtube to determin if it should use ytplay or xdg-open
if command -v www >/dev/null; then
	Player='www'
else
	Player='xdg-open'
fi
echo "${tutorials}" | grep -P "^$(echo "${tutorials}" | grep "https\?:" | sed 's/\t.*//g' | ${LAUNCER} "Learn about what?" | cut -f1)\t" | sed 's/.*\t//' | xargs -r ${Player}
#vim:ft=sh
