#!/bin/bash

#this script sends a notification stating the current brightness precentage

# xbacklight -get | while read OUTPUT; 
# do dunstify -r 325 "💡  $OUTPUT%"; done
# int=${float%.*}

OUTPUT="$(xbacklight -get)"
ROUNDED=${OUTPUT%.*}
dunstify -t 500 -r 325 "Light: $ROUNDED%"
