#!/bin/sh

# A general backlight interface
notifybrightness() {
	# BRIGHTNESS=$(bright)
	# dunstify -t 500 -r 325 "Light: $BRIGHTNESS"
	# xsetroot -name "Light[$BRIGHTNESS]"
	statwe -b
}
backlight() {
        file=/sys/class/backlight/intel_backlight/brightness
	current=$(cat $file)
	max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
	new="$current"
	if [ "$1" = "-inc" ]
	then
	    new=$(echo "current + (1000 * $2)" | bc)
	fi
	if [ "$1" = "-dec" ]
	then
	    new=$(echo "current - (1000 * $2)" | bc)
	fi
	echo "$new" | tee "$file"
}

[ -z "$2" ] && num="2" || num="$2"

case "$1" in
u*)
	# backlight -inc "$num"
	xbacklight -inc "$num"
	notifybrightness
	;; #change the default audio sync
d*)
	# backlight -dec "$num"
	xbacklight -dec "$num"
	notifybrightness
	;; #change the default audio sync
*) cat <<EOF ;;

Allowed options:
  up NUM	Increase brightness (2 secs default)
  down NUM	Decrease brightness (2 secs default)
  all else	Print this message

All of these commands, except for \`up\` and \`down\` can be truncated,
i.e. \`$( basename $0 ) u\` for \`$( basename $0 ) up\`.
EOF
esac
