#!/bin/sh

NUM="${2:-5}"

# Get the selected sink volume
updatevolume() { statwe -a; }

# Uncomment the following line to use Pulseaudio.
PIPEWIRE=true
if [ "$PIPEWIRE" ]; then
	toggle() { pactl set-sink-mute @DEFAULT_SINK@ toggle; }
	up() { pactl set-sink-volume @DEFAULT_SINK@ +"${NUM}"%; }
	down() { pactl set-sink-volume @DEFAULT_SINK@ -"${NUM}"%; }
	control() { pulsemixer; }
	connect() { njconnect; }
else
	toggle() { amixer sset Master toggle; }
	up() { amixer sset Master "${NUM}"%+; }
	down() { amixer sset Master "${NUM}"%-; }
	control() { alsamixer; }
fi

case "$1" in
mute) toggle ;;
up) up ;;
down) down ;;
*)
	control
	exit 0
	;;
esac
updatevolume
