#!/bin/sh
intern=eDP1
monitors='
DP2
HDMI2'

_mappings(){
	remaps 2>/dev/null &
}

_highdpi() {
 xrandr --dpi 220
}

_if_monitor_connected() {
	for monitor in $monitors; do
		xrandr --output "$intern" --primary --auto --output "$monitor" --right-of "$intern" --auto
	done
}

_if_disconnected() {
xrandr | grep "$monitor disconnected" &&
	xrandr --output "$monitor" --off --output "$intern" --auto
}
_if_monitor_connected

_if_disconnected

device=$(uname -n)
[ "$device" = "sp4" ] && _highdpi
setbg &
_mappings
# vim:ft=sh
