#!/bin/env sh
docker_reset() {
	docker rm -vf $(docker ps -aq)
	docker rmi -f $(docker images -aq)
	docker system prune -a --volumes
	# delete all volumes
	docker volume rm $(docker volume ls -q --filter dangling=true)
}

docker_reset
