#!/bin/sh
# intern=eDP-1
intern=eDP1
monitors=$(xrandr | awk "/ connected/ { if (\$1 != \"$intern\") print \$1;}")
left=$(echo $monitors | cut -d' ' -f1)
right=$(echo $monitors | cut -d' ' -f2)
# 'DP2
# DP-2
# HDMI2'
echo $left
_mappings() {
	remaps 2>/dev/null &
}

_highdpi() {
	xrandr --dpi 220
}

_if_monitor_connected() {
	if [ "$(echo ${monitors} | wc -l)" = "2" ]; then
	    echo path 1
	    xrandr --output "$left" --auto
	    xrandr --output "$right" --auto

	    xrandr --output "$intern" --primary --auto --output "$left" --left-of "$intern" --auto --output "$right" --right-of "$intern" --auto
	elif [ "$(echo ${monitors} | wc -l)" = "1" ]; then
	    echo left is $left and internal is $intern
	    xrandr --output "$intern" --primary --auto --output "$left"  --auto --left-of "$intern"
	fi
}

_if_disconnected() {
	xrandr | grep "$monitor disconnected" &&
		xrandr --output "$monitor" --off --output "$intern" --auto
}
_if_monitor_connected

_if_disconnected

device=$(uname -n)
[ "$device" = "sp4" ] && _highdpi
setbg &
_mappings
# vim:ft=sh
