#!/bin/sh

# Feed script a url.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.
# cant use environmental variables
# If no url given. Opens browser. For using script as $BROWSER.

OS="$(uname -o)" # this is for use with termux
if [ "$OS" = 'Android' ];then
    [ -z "$1" ] && { xdg-open "https://duckduckgo.com"; exit; }
    xdg-open "$1"
    exit
fi
echo "$1"
[ -z "$TRUEBROWSER" ] && TRUEBROWSER="surf"
[ -z "$1" ] && { $TRUEBROWSER "https://duckduckgo.com"; exit; }
case "$1" in
    *mkv|*webm|*mp4|*gif|*hooktube.com*|*v.redd.it*|*view_video*)
	setsid mpv --really-quiet "$1" >/dev/null 2>&1 &
	notify-send "Playing Video";;
    *youtube.com/watch*|*youtube.com/playlist*) #limit the video quality
	ytplay "$1" &;;
    *reddit.com/r/*) #limit the video quality
	setsid "$TERMINAL" rtv "$1" &;;
    *png|*jpg|*jpe|*jpeg)
	curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && imv "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
	# curl "$1" | imv - ;;
    *pdf)
	curl "$1" | "$READER" - >/dev/null 2>&1 & ;;
    *mp3|*m4a|*ogg|*flac|*opus|*mp3?source|*soundcloud*)
	setsid "$TERMINAL" -n "mp3" -e mpv --video=no "$1" >/dev/null 2>&1 & ;;
    *imgur.com/*)
	url=$(curl -s "$1" | grep "/i.imgur.com/" | grep "link" | cut -d'"' -f4)
	curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///")" && setsid imv "/tmp/$(echo "$url" | sed "s/.*\///")"   & ;;
    *.diff|*.md|*.txt|*.c|*.h|*.cpp|*.hs|*.py|*raw*)
	curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && setsid "$TERMINAL" -n popup -e "$EDITOR" "/tmp/$(echo "$1" | sed "s/.*\///")"   & ;;
    *) 
	setsid "$TRUEBROWSER" "$1" >/dev/null 2>&1 & ;;
esac
