#!/bin/dash

# A general audio interface for LARBS.

# utilises dunstify ant amixer to notify the 
# user of the volume as well as chang it
# Get the index of the selected sink:
getsink() {
    pacmd list-sinks | awk '/index:/{i++} /* index:/{print i; exit}'
    
}
# Get the selected sink volume
getvolume() {
    volume="$(pactl list sinks | grep 'Mute: yes')"
    # [ -n "$volume" ] &&  /usr/bin/dunstify -r 798 -t 500 "🔈 MUTE" && exit
    # [ -n "$volume" ] &&  xsetroot -name "🔈 MUTE" && exit
    [ -n "$volume" ] &&  xsetroot -name "🔈 MUTE" && exit

    volume=$(pacmd list-sinks | awk '/^\svolume:/{i++} i=='"$(getsink)"'{print $5; exit}')
    # /usr/bin/dunstify -r 798 -t 500 "Volume: ${volume}"
    xsetroot -name "$(~/Programming/C_practice/statwe/statwe -a)"
}

[ -z "$2" ] && num="2" || num="$2"

case "$1" in
	# u*) pulsemixer --change-volume +"$num" ;;#Speakers and headphones SLOW
	# u*) pactl set-sink-volume 0 +"$num"% ;pactl set-sink-volume 2 +"$num"% ;;#Speakers and headphones
	# u*) pactl set-sink-volume 0 +"$num"% ;; #Speakers
	# u*) pactl set-sink-volume 2 +"$num"% ;;#headphones 
	u*) pactl set-sink-volume @DEFAULT_SINK@  +"$num"% ; getvolume;;#change the default audio sync
	# d*) pulsemixer --change-volume -"$num" ;;#Speakers and headphones SLOW
	# d*) pactl set-sink-volume 0 -"$num"% ;pactl set-sink-volume 2 -"$num"% ;;#Speakers and headphones
	# d*) pactl set-sink-volume 0 -"$num"% ;;#Speakers
	# d*) pactl set-sink-volume 2 -"$num"% ;;#headphones
	d*) pactl set-sink-volume @DEFAULT_SINK@  -"$num"% ; getvolume;;#change the default audio sync
	m*) pulsemixer --toggle-mute ; getvolume;;
	truemute) pulsemixer --mute ;;
	play) dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play;;
	n*) dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next ;;
	prev) dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous ;;
	t*) 
            [ -z "$(pgrep spotify)" ] && spotify
            dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause ;;
	p*) dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop ;;
	f*) mpc seek +"$num" ;;
	b*) mpc seek -"$num" ;;
	r*) mpc seek 0\% ;;
	*) cat << EOF
lmc: cli music interface for mpd and pulse for those with divine intellect too
grand to remember the mpc/pamixer commands.

Allowed options:
  up NUM	Increase volume (2 secs default)
  down NUM	Decrease volume (2 secs default)
  mute		Toggle mute
  truemute	Mute
  next		Next track
  prev		Previous track
  toggle	Toggle pause
  truepause	Pause
  foward NUM	Seek foward in song (2 secs default)
  back NUM	Seek back in song (2 secs default)
  restart	Restart current song
  all else	Print this message

All of these commands, except for \`truemute\`, \`prev\` and \`play\` can be truncated,
i.e. \`lmc r\` for \`lmc restart\`.
EOF
esac
