#!/bin/sh

NUM="${2:-5}"

# Get the selected sink volume
updatevolume() { statwe -a; }

# Uncomment the following line to use Pulseaudio.
# PULSE=true
if [ "$PULSE" ]; then
	toggle() { pactl set-sink-mute @DEFAULT_SINK@ toggle; }
	mute() { pactl set-sink-mute @DEFAULT_SINK@ 1; }

	up() { pactl set-sink-volume @DEFAULT_SINK@ +"${NUM}"%; }
	down() { pactl set-sink-volume @DEFAULT_SINK@ -"${NUM}"%; }
	control() { pulsemixer; }
else
	toggle() { amixer sset Master toggle; }
	mute() { amixer sset Master mute; }
	up() { amixer sset Master "${NUM}"%+; }
	down() { amixer sset Master "${NUM}"%-; }
	control() { alsamixer; }
fi

case "$1" in
toggle) toggle ;;
mute) mute ;;
up) up ;;
down) down ;;
*)
	control
	exit 0
	;;
esac
updatevolume
