#!/bin/bash
#pomodoro
recordTomato () {
notify-send "pomodoro" "break"
mpv /usr/share/sounds/freedesktop/stereo/message.oga
exec 3>&1
exec 3>&-;
runBreak
}

runTomato () {
notify-send "pomodoro" "Start tomato"
mpv /usr/share/sounds/freedesktop/stereo/message.oga
  seconds=1500;
  date1=$((`date +%s` + seconds));
while [ "$date1" -ge "$(date +%s)" ];
do
  dialog --infobox "Work for $(date -u --date @$(($date1 - `date +%s` )) +%H:%M:%S)" 10 30 ; sleep 1
done
recordTomato
}

runBreak () {
  seconds=300;
date1=$((`date +%s` + seconds));

while [ "$date1" -ge "$(date +%s)" ];
do
  dialog --infobox "Nice work
  Now you're on break!
  rest for $(date -u --date @$(($date1 - "$(date +%s)" )) +%H:%M:%S)" 0 0 ; sleep 1
done
runTomato
}

runTomato
