#!/usr/bin/env sh

######################################################################
# @author      : Gavin Jaeger-Freeborn (gavinfreeborn@gmail.com)
# @file        : qrrecieve.sh
# @created     : Sat 18 Jul 2020 10:56:00 PM
#
# @description : Quick way to send text from your phone yo your computer
######################################################################

# Requires:
#          oneshot
#          curl or qrencode

port=6967
tmpdir="/tmp/qrrecieve"
tmpqr="/tmp/QR.png"
timeout="30s"

add="http://$(ip ad | grep 'inet ' | awk 'NR > 1 {print $2}' | cut -d'/' -f1):$port"

# TODO: finish optional google qrcode <19-07-20 Gavin Jaeger-Freeborn>
qrurl() 
{ 
	curl -sS "http://chart.apis.google.com/chart?chs=200x200&cht=qr&chld=H|0&chl=$1" -o "${tmpqr}"
}

shout()
{
  echo "$*"
  notify-send "$*"
  exit 1
}

if command -v qrencode >/dev/null ;then
	echo "${add}" | qrencode -s 10 -o "${tmpqr}"
else
	qrurl "${add}"
fi

# Check if port is in use
lsof -i -P | grep ".*:$port.*" && shout "port $port is in use"

xdg-open "${tmpqr}" &

oneshot --timeout "$timeout" --port $port --upload-input | xclip

# vim: set tw=78 ts=2 et sw=2 sr:
