#!/bin/sh
! echo "$1" | grep "https*://\S\+\.[A-Za-z]\+\S*" >/dev/null &&
	notify-send "That doesn't look like a full URL." && exit
RSSFILE="$HOME/.config/newsboat/urls"
if awk '{print $1}' "$RSSFILE" | grep "^$1$" >/dev/null; then
	notify-send "You already have this RSS feed."
else
	RSSSTRING="$1"
	RSSNAME="$(echo "News" | dmenu -p "rss feed name")"
	[ -z "$RSSNAME" ] notify-send "Canceled adding rss." && exit
	if [ "$RSSNAME" != News ]; then
		RSSSTRING="\"~${RSSSTRING} $RSSNAME\""
	fi
	echo "$RSSSTRING" >>"$RSSFILE" && notify-send "RSS feed added."
fi
