#!/bin/sh
# Sets the background. If given an argument, will set file as background.
[ ! -z "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "Wallpaper changed."
xsetroot -grey
# xwallpaper --stretch ~/.config/wall.png
