#!/usr/bin/sh
curl -s "http://datapoint.metoffice.gov.uk/public/data/val/wxobs/all/json/3330?res=hourly&key=ae11db48-43bd-4d62-b58e-759a09115d6d" | jq '.[] | {temp: .DV.Location.Period[-1].Rep[-1].T}' | sed '2q;d' | cut -d ' ' -f 4 | sed 's/\"//g' | sed 's/$/°C/g'
exit
