#!/usr/bin/sh

# script they plays youtube videos that opens a youtube video in
# the best available quality up to 480p since more then that
# is bloat

notify-send "Playing video"
# try to run video in lower format
allcpus_enabled=$(cat /sys/devices/system/cpu/cpu1/online)
charging_state=$(cat /sys/class/power_supply/BAT0/status)

if [ "$allcpus_enabled" -eq 0 ]; then
	# 360p if not all cores are enabled
	setsid mpv --force-window=immediate --really-quiet\
		--ytdl-format="bestvideo[height<=?360]+bestaudio/best" "$*" >/dev/null 2>&1 &&
		exit
elif [ "$charging_state" = 'Charging' ]; then
	# Default to 720p if charging
	setsid mpv --force-window=immediate --really-quiet\
		--ytdl-format="bestvideo[height<=?720]+bestaudio/best" "$*" >/dev/null 2>&1 && 
		exit
else
	# Default to 480p
	setsid mpv --force-window=immediate --really-quiet\
		--ytdl-format="bestvideo[height<=?480]+bestaudio/best" "$*" >/dev/null 2>&1 && 
		exit
fi

# video cannot me loaded
notify-send "Failed to play Video"
#vim:ft=sh
