#!/bin/sh
[ -z "$LAUNCHER" ] && LAUNCHER="fzf --tac"
if [ $TERM = dumb ] ; then
    mshow -t .
    read ATTACH
else
    ATTACH="$(mshow -t . | $LAUNCHER)"
fi    
[ -z "$ATTACH" ] && exit 1
MIME="$(echo "$ATTACH" | cut -f 2 -d ":" | cut -f 2 -d " ")"
ATTACHNUM="$(echo "$ATTACH" | cut -f1 -d':')"

tmp="$(mktemp '/tmp/mblaze.XXXXXX')"
mshow -O . "$ATTACHNUM" > "$tmp"
case "$MIME" in
	*)
		xdg-open "$tmp";;
esac
